### ISSUE TITLE
Latest version of Sweet Build fails on macOS Sierra

### ISSUE THREAD

**Issue by willmbaker** [cwbaker/forge#1]
I updated to the latest version and I get this error when building:

`The type 'string' at position 1 is not 'N5sweet10build_tool9BuildToolE' as expected`

I've tried doing a clean build, deleting the `build` directory, etc. Ended up having to roll back to `4214d75` in order to get it working again.

**Comment by cwbaker** [comment]
Sorry Will.  I think that will have be me breaking backwards compatibility between the executable and your build scripts.  Perhaps try starting again if you're still working on it?  I don't think you are though so I will just close this ticket.

Thanks,
Charles.
