### ISSUE TITLE
Builds fail when using devtoolset on Centos-7

### ISSUE THREAD

**Issue by harmic** [cwbaker/forge#22]
I am using a Centos 7 environment, together with [devtoolset-7](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/) (in order to get more recent compilers).

With devtoolset enabled in a shell:

```
$ which gcc
/opt/rh/devtoolset-7/root/usr/bin/gcc
```

However when trying to build forge I get the following error for each compilation:

```
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
```

cc1plus is available:

```
$ find /opt/rh/devtoolset-7/ -name cc1plus
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/cc1plus
```

Also I can compile C++ programs manually or using other build systems, so I think it must be something  specific to Forge that is causing this.

Dropping back to the regular gcc supplied with Centos 7 allows it to build successfully.

**Comment by cwbaker** [comment]
Thanks for the report Mike.

At a guess Forge is not setting PATH correctly in the environment. That will be in gcc.initialize() in gcc.lua IIRC and you're in the mood to take a look.

Otherwise I have some time tomorrow and should be able to fix it then.

Thanks,
Charles

**Comment by cwbaker** [comment]
Actually gcc.configure() https://github.com/cwbaker/forge/blob/5057a71a6b58632da735ff2bd9128390268c8a41/src/forge/lua/forge/cc/gcc.lua#L10

Definitely PATH not set correctly is the problem.

**Comment by cwbaker** [comment]
@harmic Thanks for the clear bug report.  Pretty sure that should be fixed now.  I tested in the CentOS `devtoolset-7` Docker image and was able reproduce the same problem.  Fixed and merged to main.  Let me know if that's not the case for you and I'll reopen the issue.

**Comment by harmic** [comment]
Brilliant, thanks @cwbaker. 
Works for me.
