### ISSUE TITLE
When I run the bootstrap script on macOS Sierra I get compilation errors

### ISSUE THREAD

**Issue by willmbaker** [cwbaker/forge#3]
I was following the installation instructions and when running the following command:
`bash ./bootstrap-macos.bash` I got compilation errors:

```
~/insertcoin/process/thirdparty/forge/src/luaxx ~/insertcoin/process/thirdparty/forge
luaxx.cpp...
luaxx.cpp:503:9: error: use of undeclared identifier 'free'
        free( ptr );
        ^
luaxx.cpp:508:16: error: use of undeclared identifier 'realloc'
        return realloc( ptr, nsize );
               ^
2 errors generated.
ar: *.o: No such file or directory
```
This is macOS Sierra, where `clang --version` outputs:

```
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by cwbaker** [comment]
Thanks for the excellent bug report Will.

I don't have access to macOS Sierra but at a guess I've just included the wrong headers in *luaxx.cpp*.  Try pulling from *master* now where I've included *stdlib.h* and *string.h* to match what documentation tells me is required for those functions.  Let me know how it goes.

Alternatively you can get prebuilt binaries from Github Releases now too.  The latest is [v0.0.2-rc.6](https://github.com/cwbaker/forge/releases/tag/v0.0.2-rc.6).

**Comment by willmbaker** [comment]
Choice! That worked perfectly. Thank you :)
