### ISSUE TITLE
Windows installation doesn't produce forge.exe

### ISSUE THREAD

**Issue by Rayshard** [cwbaker/forge#6]
After running the bootstrap-windows.bat, the forge.exe is never produce.

**Comment by cwbaker** [comment]
Thanks for trying it out.  Can you please answer a few questions?

1. What is the output from running *bootstrap-windows.bat*?
2. Which version of Microsoft Visual C++ are you using?

Thanks,
Charles

**Comment by Rayshard** [comment]
Thanks for replying!
1. The bootstrap-windows.bat output is as follows (it seems that there were some linking issues):

[bat_output.txt](https://github.com/cwbaker/forge/files/4373253/bat_output.txt)

2. I'm using Visual C++ 19

Best,
Ray

**Comment by cwbaker** [comment]
Hi Ray,

I've managed to reproduce the same problem here by compiling from the "x86 Native Tools Command Prompt" which is compiling for 32-bit architecture.  Are  you able to build from the "x64 Native Tools Command Prompt" instead?

I'm assuming that you've got a 64-bit machine and Windows version.  If not I can see if I can get it to build for 32-bit but it will be missing automatic dependency detection and hashing of settings.  Forge in 32-bit mode would most likely always miss those features -- it's possible to support them but I don't really want to take on that maintenance burden if I don't have to.

Thanks,
Charles

**Comment by Rayshard** [comment]
Yep, it works now! Thanks for the quick responses!

**Comment by cwbaker** [comment]
Awesome!  Thanks Ray and good luck!
