### ISSUE TITLE
This is more of a question, sorry, can't figure out how to comment on a line :P

### ISSUE THREAD

**Issue by willmbaker** [cwbaker/forge#9]
https://github.com/cwbaker/forge/blob/075287cfd46285813dfc391f8ea16ddcc762c47a/src/forge/stdafx.cpp#L1

What does "AFX" stand for?

**Comment by cwbaker** [comment]
I don't know.  That was the default name for Visual Studio precompiled
headers and I've just carried that header file through from there.
